"""add_content_type_and_provenance

Revision ID: 2d4f82931dcc
Revises: 4e8910a51c91
Create Date: 2026-09-13 01:23:03.857193

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d4f82931dcc'
down_revision: Union[str, Sequence[str], None] = '4e8910a51c91'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('articles', sa.Column('content_type', sa.Text(), server_default='article', nullable=False))
    op.add_column('sources', sa.Column('provenance', sa.Text(), server_default='independent', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'provenance')
    op.drop_column('articles', 'content_type')
    # ### end Alembic commands ###
