"""add source_family to sources

Revision ID: 339be5e01b20
Revises: 7dc6c2a375df
Create Date: 2026-09-13 00:01:16.133194

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '339be5e01b20'
down_revision: Union[str, Sequence[str], None] = '7dc6c2a375df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('articles', 'primary_category',
               existing_type=sa.VARCHAR(length=100),
               type_=sa.Text(),
               existing_nullable=True)
    op.add_column('sources', sa.Column('source_family', sa.Text(), server_default='news', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sources', 'source_family')
    op.alter_column('articles', 'primary_category',
               existing_type=sa.Text(),
               type_=sa.VARCHAR(length=100),
               existing_nullable=True)
    # ### end Alembic commands ###
