"""add_article_ai_outputs_table

Revision ID: 352c665694b2
Revises: 2d4f82931dcc
Create Date: 2026-09-13 02:03:37.191310

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '352c665694b2'
down_revision: Union[str, Sequence[str], None] = '2d4f82931dcc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('article_ai_outputs',
    sa.Column('id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), autoincrement=True, nullable=False),
    sa.Column('article_id', sa.BigInteger().with_variant(sa.Integer(), 'sqlite'), nullable=False),
    sa.Column('provider', sa.Text(), server_default='ollama', nullable=False),
    sa.Column('model', sa.Text(), server_default='qwen3.5:4b', nullable=False),
    sa.Column('task', sa.Text(), server_default='article_analysis', nullable=False),
    sa.Column('prompt_version', sa.Text(), server_default='v1', nullable=False),
    sa.Column('output_json', sa.JSON(), nullable=True),
    sa.Column('summary', sa.Text(), nullable=True),
    sa.Column('primary_category', sa.Text(), nullable=True),
    sa.Column('importance_score', sa.Integer(), nullable=True),
    sa.Column('relevance_score', sa.Integer(), nullable=True),
    sa.Column('status', sa.Text(), server_default='success', nullable=False),
    sa.Column('processed_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('processing_ms', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['article_id'], ['articles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('article_id', 'provider', 'model', 'task', 'prompt_version', name='uix_article_ai_output_provider_model_task_version')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('article_ai_outputs')
    # ### end Alembic commands ###
